FROM tomcat:9.0.106-jdk8-corretto-al2

# Install SSH server and sudo
RUN yum update -y && \
    yum install -y openssh-server sudo passwd unzip gzip tar wget && \
    yum clean all && \
    rm -rf /var/cache/yum

# Set root password (change this in real use!)
RUN echo "root:rootpassword" | chpasswd

# Allow root login via SSH
RUN sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

# Delete UseDNS and GSSAPIAuthentication options and set them to no for Windows SSH delay fix
RUN sed -i '/UseDNS/d; /GSSAPIAuthentication/d' /etc/ssh/sshd_config && \
    echo "UseDNS no" >> /etc/ssh/sshd_config && \
    echo "GSSAPIAuthentication no" >> /etc/ssh/sshd_config

# Create run dir
RUN mkdir -p /var/run/sshd

# Init default webapps
RUN cp -R /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps

# Install log4j jar to test vulnerabilities check
RUN wget -P /usr/local/tomcat/lib/ https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar

# Generate host keys at build time
RUN ssh-keygen -A

EXPOSE 8080 22

# Start SSH and Tomcat
CMD /usr/sbin/sshd && catalina.sh run
